platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet

inputs:
- name: AspNetDotNetCoreDemo-Git
outputs:
- name: AspNetDotNetCoreDemo-app

run:
  path: sh
  args: ["AspDotNetCoreDemo/ci/build.sh"]